name: 'Publish Maven Central'

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish Maven Central
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '19'

      - name: Prepare GPG Key for Sign Package
        run: |
          echo "${{ secrets.MAVEN_GPG }}" | base64 -d > secring.gpg

      - name: Publish
        run: |
          ./gradlew -PossrhUsername="${OSSRH_USERNAME}" -PossrhPassword="${OSSRH_PASSWORD}" -Psigning.keyId="${SIGN_KEY_ID}" -Psigning.password="${SIGN_PASSWORD}" -Psigning.secretKeyRingFile="`pwd`/secring.gpg" -PsonatypeStagingProfileId="${SONATYPE_STAGING_PROFILE_ID}" publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: "${{ secrets.OSSRH_USERNAME }}"
          OSSRH_PASSWORD: "${{ secrets.OSSRH_PASSWORD }}"
          SIGN_KEY_ID: "${{ secrets.SIGN_KEY_ID }}"
          SIGN_PASSWORD: "${{ secrets.SIGN_PASSWORD }}"
          SONATYPE_STAGING_PROFILE_ID: "${{ secrets.SONATYPE_STAGING_PROFILE_ID }}"
